// Voimareitti deeper nutrition content - expandable topics for the Nutrition page.
// Calm, evidence-based, food-first, NON-medical (no disease claims, no prescriptions).
// Numbers reflect general consensus (NNR 2023 / Finnish 2024 guidance, ACSM/NSCA,
// flexible-dieting literature), never a single athlete's protocol.
// CLAUDE.md Hard Rules: no em/en dashes (plain hyphen only); correct diacritics.
// EN + FI required per paragraph; HU/SV may be omitted and fall back to EN via L().

import type { Loc } from './data';

export interface NutritionTopic {
	id: string;
	title: Loc; // 4 languages, short
	summary: Loc; // 4 languages, one sentence shown collapsed
	body: Loc[]; // 2-4 paragraphs; EN + FI required (HU/SV optional)
}

export const nutritionTopics: NutritionTopic[] = [
	{
		id: 'energy-balance',
		title: {
			en: 'Energy balance',
			fi: 'Energiatasapaino',
			hu: 'Energiamérleg',
			sv: 'Energibalans'
		},
		summary: {
			en: 'Calories in versus calories out decides whether you lose or gain - everything else is fine-tuning.',
			fi: 'Syödyt ja kulutetut kalorit ratkaisevat, putoatko vai nousetko - kaikki muu on hienosäätöä.',
			hu: 'A bevitt és elhasznált kalória dönti el, hogy fogysz vagy hízol - minden más finomhangolás.',
			sv: 'Kalorier in mot kalorier ut avgör om du tappar eller ökar - allt annat är finjustering.'
		},
		body: [
			{ en: 'Body weight follows one simple rule over time: eat fewer calories than you burn and you lose fat; eat more and you gain. A calorie is the unit of energy in food. No food, macro split, or meal time overrides this balance, so it is the first thing to get roughly right.', fi: 'Paino seuraa ajan myötä yksinkertaista sääntöä: syö vähemmän kaloreita kuin kulutat, niin pudotat rasvaa; syö enemmän, niin nouset. Kalori on ruoan energian yksikkö. Mikään ruoka, makrojako tai ateria-aika ei kumoa tätä tasapainoa, joten se kannattaa saada ensin suunnilleen kohdalleen.', hu: 'A testsúly hosszú távon egyetlen egyszerű szabályt követ: ha kevesebb kalóriát eszel, mint amennyit elégetsz, zsírt vesztesz; ha többet, hízol. A kalória az élelmiszerben lévő energia mértékegysége. Semmilyen étel, makróarány vagy étkezési időpont nem írja felül ezt az egyensúlyt, ezért elsőként ezt érdemes nagyjából eltalálni.', sv: 'Kroppsvikten följer en enkel regel över tid: ät färre kalorier än du förbrukar så tappar du fett; ät fler så går du upp. En kalori är enheten för energi i mat. Ingen mat, makrofördelning eller måltidstidpunkt upphäver den här balansen, så det är det första du bör få någorlunda rätt.' },
			{ en: 'You do not need a perfect number. A reasonable starting estimate is your body weight in kilograms times roughly 30-33 kcal per day for a fairly active person, or use the apps estimate as a starting point. Treat it as a hypothesis to test, not a fact.', fi: 'Et tarvitse täydellistä lukua. Järkevä lähtöarvio on paino kiloina kerrottuna noin 30-33 kcal:lla päivässä melko aktiiviselle henkilölle, tai käytä sovelluksen arviota lähtökohtana. Pidä sitä testattavana oletuksena, ei totuutena.', hu: 'Nem kell tökéletes szám. Ésszerű kiindulási becslés egy viszonylag aktív embernél a testsúly kilogrammban szorozva nagyjából napi 30-33 kcal-val, vagy használd kiindulópontként az alkalmazás becslését. Kezeld tesztelendő feltevésként, ne tényként.', sv: 'Du behöver ingen perfekt siffra. En rimlig utgångspunkt är din kroppsvikt i kilo gångrat med ungefär 30-33 kcal per dag för en ganska aktiv person, eller använd appens uppskattning som startpunkt. Se det som en hypotes att testa, inte ett faktum.' },
			{ en: 'Then let the scale and the mirror tell you the truth over two to three weeks. If the weekly average is moving the way you want, the estimate is close enough. If it is flat when you want change, adjust food by a small amount (about 150-250 kcal) and watch again. Slow and steady beats guessing daily.', fi: 'Anna sitten vaa\'an ja peilin kertoa totuus kahden tai kolmen viikon aikana. Jos viikkokeskiarvo liikkuu haluamaasi suuntaan, arvio on riittävän lähellä. Jos se pysyy paikallaan kun haluat muutosta, säädä ruokaa pienesti (noin 150-250 kcal) ja seuraa uudelleen. Hidas ja tasainen voittaa päivittäisen arvailun.', hu: 'Aztán hagyd, hogy a mérleg és a tükör mondja meg az igazat két-három hét alatt. Ha a heti átlag a kívánt irányba mozdul, a becslés elég közeli. Ha nem mozdul, holott változást szeretnél, módosítsd az étkezést egy kis lépéssel (nagyjából 150-250 kcal) és figyeld újra. A lassú és kitartó megközelítés legyőzi a napi találgatást.', sv: 'Låt sedan vågen och spegeln berätta sanningen över två till tre veckor. Om veckosnittet rör sig åt det håll du vill är uppskattningen tillräckligt nära. Om det står stilla när du vill ha förändring, justera maten med en liten mängd (ungefär 150-250 kcal) och följ upp igen. Långsamt och stadigt slår daglig gissning.' }
		]
	},
	{
		id: 'protein',
		title: {
			en: 'Protein',
			fi: 'Proteiini',
			hu: 'Fehérje',
			sv: 'Protein'
		},
		summary: {
			en: 'Aim for about 1.6-2.2 g per kg of body weight a day, spread over the day; it protects and builds muscle.',
			fi: 'Tavoittele noin 1,6-2,2 g painokiloa kohti päivässä, jaettuna päivälle; se suojaa ja rakentaa lihasta.',
			hu: 'Célozz kb. 1,6-2,2 g-ot testtömegkilogrammonként naponta, elosztva; védi és építi az izmot.',
			sv: 'Sikta på cirka 1,6-2,2 g per kg kroppsvikt om dagen, fördelat; det skyddar och bygger muskler.'
		},
		body: [
			{ en: 'Protein is the building material for muscle and the nutrient that matters most when you train. A practical daily target is about 1.6-2.2 g per kilogram of body weight. When you are in a calorie deficit and want to keep muscle, the upper end and even up to about 2.4 g/kg can help. Below roughly 1.6 g/kg you leave easy progress on the table.', fi: 'Proteiini on lihaksen rakennusaine ja tärkein ravintoaine, kun harjoittelet. Käytännön päivätavoite on noin 1,6-2,2 g painokiloa kohti. Kun olet kalorivajeessa ja haluat säilyttää lihasta, ylälaita ja jopa noin 2,4 g/kg voi auttaa. Alle noin 1,6 g/kg jätät helppoa kehitystä käyttämättä.', hu: 'A fehérje az izom építőanyaga és a legfontosabb tápanyag, amikor edzel. Gyakorlatias napi célérték nagyjából 1,6-2,2 g testsúlykilogrammonként. Amikor kalóriadeficitben vagy és meg akarod tartani az izmot, a felső határ, sőt akár nagyjából 2,4 g/kg is segíthet. Nagyjából 1,6 g/kg alatt könnyű fejlődést hagysz az asztalon.', sv: 'Protein är byggmaterialet för muskler och det näringsämne som betyder mest när du tränar. Ett praktiskt dagligt mål är ungefär 1,6-2,2 g per kilo kroppsvikt. När du är i ett kaloriunderskott och vill behålla muskler kan den övre delen och till och med upp till cirka 2,4 g/kg hjälpa. Under ungefär 1,6 g/kg lämnar du lätt framsteg outnyttjade.' },
			{ en: 'Spread it across three to four meals rather than loading it all at once. There is no hard limit on how much protein the body can use from a single meal; spreading it simply makes the daily total easier to reach and keeps you full. Roughly 25-40 g of protein per meal is a comfortable, practical range for most people.', fi: 'Jaa se kolmelle tai neljälle aterialle sen sijaan, että söisit kaiken kerralla. Keholla ei ole tiukkaa ylärajaa sille, kuinka paljon proteiinia se voi käyttää yhdeltä aterialta; jakaminen vain helpottaa päivätavoitteen saavuttamista ja pitää kylläisenä. Noin 25-40 g proteiinia ateriaa kohti on useimmille mukava ja käytännöllinen vaihteluväli.', hu: 'Oszd el három-négy étkezésre, ahelyett hogy mindet egyszerre vinnéd be. Nincs szigorú felső határa annak, mennyi fehérjét tud a szervezet egyetlen étkezésből felhasználni; az elosztás egyszerűen csak megkönnyíti a napi cél elérését és tartja a jóllakottságot. Nagyjából 25-40 g fehérje étkezésenként a legtöbb embernek kényelmes, gyakorlatias tartomány.', sv: 'Sprid ut det över tre till fyra måltider istället för att ta allt på en gång. Det finns ingen hård gräns för hur mycket protein kroppen kan använda från en enda måltid; att sprida ut det gör bara dagstotalen lättare att nå och håller dig mätt. Ungefär 25-40 g protein per måltid är ett bekvämt och praktiskt intervall för de flesta.' },
			{ en: 'Good sources are easy to find: chicken, fish, eggs, lean meat, dairy such as quark and skyr, plus plant options like tofu, beans, lentils and soy products. A protein powder is just a convenient food if whole food falls short on a given day, not a requirement.', fi: 'Hyviä lähteitä on helppo löytää: kana, kala, kananmunat, vähärasvainen liha, maitotuotteet kuten rahka ja skyr sekä kasvivaihtoehdot kuten tofu, pavut, linssit ja soijatuotteet. Proteiinijauhe on vain kätevä ruoka, jos oikea ruoka jää vajaaksi jonain päivänä, ei välttämättömyys.', hu: 'Jó forrásokat könnyű találni: csirke, hal, tojás, sovány hús, tejtermékek, mint a túró és a skyr, plusz növényi lehetőségek, mint a tofu, a bab, a lencse és a szójatermékek. A fehérjepor csak egy kényelmes étel arra az esetre, ha a teljes értékű ételből kevés jut egy adott napon, nem kötelező.', sv: 'Bra källor är lätta att hitta: kyckling, fisk, ägg, magert kött, mejeriprodukter som kvarg och skyr, plus växtbaserade alternativ som tofu, bönor, linser och sojaprodukter. Proteinpulver är bara en smidig mat om den riktiga maten inte räcker till en viss dag, inte ett krav.' }
		]
	},
	{
		id: 'meal-structure',
		title: {
			en: 'Building a meal',
			fi: 'Aterian rakentaminen',
			hu: 'Étkezés felépítése',
			sv: 'Bygga en måltid'
		},
		summary: {
			en: 'Use a simple plate: a protein, some produce, a quality carb and a little fat - timing is flexible.',
			fi: 'Käytä yksinkertaista lautasta: proteiini, kasviksia, laadukas hiilihydraatti ja hieman rasvaa - ajoitus on joustava.',
			hu: 'Egyszerű tányér: fehérje, zöldség, jó szénhidrát és kevés zsír - az időzítés rugalmas.',
			sv: 'Enkel tallrik: ett protein, lite grönt, en bra kolhydrat och lite fett - tiden är flexibel.'
		},
		body: [
			{ en: 'You do not need recipes to eat well. A reliable plate has four parts: a palm-sized portion of protein, a generous fist or two of vegetables or fruit, a fist of a quality carbohydrate such as potatoes, rice, oats or whole-grain bread, and a thumb of fat such as olive oil, nuts or avocado. Build most meals this way and the macros mostly take care of themselves.', fi: 'Et tarvitse reseptejä syödäksesi hyvin. Toimiva lautanen on neljässä osassa: kämmenen kokoinen annos proteiinia, runsas nyrkillinen tai kaksi kasviksia tai hedelmiä, nyrkillinen laadukasta hiilihydraattia kuten perunaa, riisiä, kauraa tai täysjyväleipää, ja peukalon verran rasvaa kuten oliiviöljyä, pähkinöitä tai avokadoa. Rakenna useimmat ateriat näin, niin makrot hoituvat suurelta osin itsestään.', hu: 'Nem kellenek receptek a jó táplálkozáshoz. Egy megbízható tányér négy részből áll: egy tenyérnyi adag fehérje, egy-két bőséges marék zöldség vagy gyümölcs, egy ököl minőségi szénhidrát, például burgonya, rizs, zab vagy teljes kiőrlésű kenyér, és egy hüvelyknyi zsír, például olívaolaj, dió vagy avokádó. Építsd fel így a legtöbb étkezést, és a makrók nagyrészt maguktól rendeződnek.', sv: 'Du behöver inga recept för att äta bra. En pålitlig tallrik har fyra delar: en handflatestor portion protein, en eller två rejäla nävar grönsaker eller frukt, en näve bra kolhydrat som potatis, ris, havre eller fullkornsbröd, och en tumme fett som olivolja, nötter eller avokado. Bygg de flesta måltider så här så sköter sig makrona mestadels själva.' },
			{ en: 'Meal timing is far more flexible than most people think. Three meals, four meals, or two larger meals all work; eating carbs in the evening does not make you gain fat. What matters is the total over the day and a pattern you can keep up. Pick the schedule that fits your life and hunger, not a rule you read somewhere.', fi: 'Aterioiden ajoitus on paljon joustavampi kuin useimmat luulevat. Kolme ateriaa, neljä ateriaa tai kaksi suurempaa ateriaa toimivat kaikki; hiilihydraattien syöminen illalla ei lihota. Merkitsee päivän kokonaismäärä ja rytmi, jonka jaksat ylläpitää. Valitse aikataulu, joka sopii elämääsi ja nälkääsi, ei sääntö jonka luit jostain.', hu: 'Az étkezések időzítése sokkal rugalmasabb, mint a legtöbben gondolják. A három étkezés, a négy étkezés vagy a két nagyobb étkezés mind működik; a szénhidrát esti fogyasztása nem hizlal. Az számít, mennyi a napi összmennyiség, és hogy milyen ritmust tudsz tartani. Válaszd azt a beosztást, ami az életedhez és az éhségedhez illik, ne valami szabályt, amit valahol olvastál.', sv: 'Måltidstidpunkten är långt mer flexibel än de flesta tror. Tre måltider, fyra måltider eller två större måltider fungerar alla; att äta kolhydrater på kvällen får dig inte att gå upp i fett. Det som spelar roll är totalen över dagen och ett mönster du kan hålla i längden. Välj det schema som passar ditt liv och din hunger, inte en regel du läst någonstans.' },
			{ en: 'Around training, a meal with protein and carbs in the hours before or after gives you energy and building blocks, but the exact minute is not critical. If your day is busy, just make sure the protein and the produce show up somewhere; consistency over weeks beats perfect timing on any single day.', fi: 'Treenin ympärillä proteiinia ja hiilihydraatteja sisältävä ateria tunteja ennen tai jälkeen antaa energiaa ja rakennusaineita, mutta tarkka minuutti ei ole ratkaiseva. Jos päivä on kiireinen, varmista vain että proteiini ja kasvikset ovat jossain mukana; johdonmukaisuus viikkojen yli voittaa täydellisen ajoituksen yksittäisenä päivänä.', hu: 'Az edzés körül egy fehérjét és szénhidrátot tartalmazó étkezés az edzés előtti vagy utáni órákban energiát és építőanyagot ad, de a pontos perc nem kritikus. Ha zsúfolt a napod, csak ügyelj rá, hogy a fehérje és a zöldség valahol megjelenjen; a hetekig tartó következetesség legyőzi a tökéletes időzítést egyetlen napon.', sv: 'Runt träningen ger en måltid med protein och kolhydrater under timmarna före eller efter dig energi och byggstenar, men exakt vilken minut är inte avgörande. Om dagen är hektisk, se bara till att proteinet och grönsakerna dyker upp någonstans; beständighet över veckor slår perfekt tajming en enskild dag.' }
		]
	},
	{
		id: 'carbs-and-fat',
		title: {
			en: 'Carbs and fat',
			fi: 'Hiilihydraatit ja rasva',
			hu: 'Szénhidrát és zsír',
			sv: 'Kolhydrater och fett'
		},
		summary: {
			en: 'Neither needs fearing: keep quality carbs around training and at least about 0.6-1 g/kg of fat.',
			fi: 'Kumpaakaan ei tarvitse pelätä: pidä laadukkaita hiilihydraatteja treenin ympärillä ja vähintään noin 0,6-1 g/kg rasvaa.',
			hu: 'Egyiktől sem kell félni: tarts jó szénhidrátot az edzés köré és legalább kb. 0,6-1 g/kg zsírt.',
			sv: 'Ingen behöver fruktas: ha bra kolhydrater kring träning och minst cirka 0,6-1 g/kg fett.'
		},
		body: [
			{ en: 'Once protein is set, carbohydrates and fat fill in the rest of your calories, and you can lean toward whichever you prefer. Carbohydrates are the bodys easiest fuel for hard training. Putting more of them in the meals around your workout gives you energy when you need it most, while a steady base through the day keeps you feeling good.', fi: 'Kun proteiini on asetettu, hiilihydraatit ja rasva täyttävät loput kaloreista, ja voit painottaa kumpaa vain suosit. Hiilihydraatit ovat kehon helpoin polttoaine kovaan harjoitteluun. Niiden painottaminen treenin ympärillä oleviin aterioihin antaa energiaa silloin kun sitä eniten tarvitset, ja tasainen perusta läpi päivän pitää olon hyvänä.', hu: 'Ha a fehérje megvan, a szénhidrát és a zsír tölti fel a kalóriák maradékát, és afelé súlyozhatsz, amelyiket jobban szereted. A szénhidrát a test legkönnyebb üzemanyaga a kemény edzéshez. Ha többet teszel belőle az edzés körüli étkezésekbe, akkor ad energiát, amikor a leginkább szükséged van rá, miközben egy egyenletes alap a nap során fenntartja a jó közérzeted.', sv: 'När proteinet är satt fyller kolhydrater och fett i resten av dina kalorier, och du kan luta åt vilketdera du föredrar. Kolhydrater är kroppens enklaste bränsle för tuff träning. Att lägga mer av dem i måltiderna runt ditt pass ger dig energi när du behöver den som mest, medan en stadig grund genom dagen håller måendet bra.' },
			{ en: 'Favour quality carbs most of the time: oats, potatoes, rice, whole-grain bread, fruit and legumes. They come with fibre and keep you full longer than sugary, low-fibre options. This is a preference for fullness and nutrients, not a ban; sweeter foods fit too as long as the day adds up.', fi: 'Suosi laadukkaita hiilihydraatteja suurimman osan ajasta: kauraa, perunaa, riisiä, täysjyväleipää, hedelmiä ja palkokasveja. Niissä on kuitua ja ne pitävät kylläisenä pidempään kuin sokeriset, vähäkuituiset vaihtoehdot. Tämä on kylläisyyteen ja ravintoaineisiin liittyvä mieltymys, ei kielto; makeammatkin ruoat sopivat, kunhan päivä menee tasan.', hu: 'Az idő nagy részében a minőségi szénhidrátot részesítsd előnyben: zab, burgonya, rizs, teljes kiőrlésű kenyér, gyümölcs és hüvelyesek. Ezekben rost van, és tovább tartanak jól, mint a cukros, alacsony rosttartalmú lehetőségek. Ez a jóllakottság és a tápanyagok melletti preferencia, nem tiltás; az édesebb ételek is beleférnek, amíg a nap kijön.', sv: 'Föredra bra kolhydrater för det mesta: havre, potatis, ris, fullkornsbröd, frukt och baljväxter. De kommer med fiber och håller dig mätt längre än sockriga, fiberfattiga alternativ. Det här är en preferens för mättnad och näringsämnen, inte ett förbud; sötare mat passar också in så länge dagen går ihop.' },
			{ en: 'Fat is needed for hormones and for absorbing some vitamins, so do not cut it too low. Keep at least about 0.6-1 g per kilogram of body weight per day as a floor. Above that, how much fat versus carbs you eat is mostly personal taste. Choose mostly unsaturated sources such as olive oil, nuts, seeds and oily fish.', fi: 'Rasvaa tarvitaan hormoneihin ja joidenkin vitamiinien imeytymiseen, joten älä leikkaa sitä liian alas. Pidä vähintään noin 0,6-1 g painokiloa kohti päivässä alarajana. Sen yli se, kuinka paljon syöt rasvaa tai hiilihydraatteja, on enimmäkseen makuasia. Valitse pääosin tyydyttymättömiä lähteitä kuten oliiviöljyä, pähkinöitä, siemeniä ja rasvaista kalaa.', hu: 'A zsír kell a hormonokhoz és egyes vitaminok felszívódásához, ezért ne vágd túl alacsonyra. Tarts alsó határként legalább nagyjából napi 0,6-1 g-ot testsúlykilogrammonként. Efölött az, hogy mennyi zsírt eszel a szénhidráthoz képest, többnyire ízlés kérdése. Válassz főként telítetlen forrásokat, mint az olívaolaj, a dió, a magvak és a zsíros hal.', sv: 'Fett behövs för hormoner och för att ta upp vissa vitaminer, så skär inte ner det för långt. Håll minst ungefär 0,6-1 g per kilo kroppsvikt per dag som golv. Därutöver är det mest personlig smak hur mycket fett kontra kolhydrater du äter. Välj mestadels omättade källor som olivolja, nötter, frön och fet fisk.' }
		]
	},
	{
		id: 'hydration',
		title: {
			en: 'Hydration',
			fi: 'Nesteytys',
			hu: 'Folyadékbevitel',
			sv: 'Vätska'
		},
		summary: {
			en: 'Roughly 30-35 ml per kg a day, more in heat and on training days; pale-yellow urine is the simple cue.',
			fi: 'Noin 30-35 ml painokiloa kohti päivässä, enemmän helteellä ja treenipäivinä; vaaleankeltainen virtsa on yksinkertainen merkki.',
			hu: 'Kb. 30-35 ml testtömegkilogrammonként naponta, többet melegben és edzésnapokon; a halványsárga vizelet a jelzés.',
			sv: 'Cirka 30-35 ml per kg om dagen, mer i värme och på träningsdagar; ljusgul urin är en enkel signal.'
		},
		body: [
			{ en: 'A simple baseline is about 30-35 ml of fluid per kilogram of body weight per day, which for many people lands around 2-2.5 litres. That total includes water, coffee, tea, milk and the water in food, not just plain water. You need more when it is hot, when you sweat a lot, or on heavier training days.', fi: 'Yksinkertainen lähtötaso on noin 30-35 ml nestettä painokiloa kohti päivässä, mikä on monelle noin 2-2,5 litraa. Tämä kokonaismäärä sisältää veden, kahvin, teen, maidon ja ruoan veden, ei vain pelkkää vettä. Tarvitset enemmän kun on kuuma, kun hikoilet paljon tai raskaampina treenipäivinä.', hu: 'Egy egyszerű alapérték nagyjából napi 30-35 ml folyadék testsúlykilogrammonként, ami sok embernél 2-2,5 liter körül alakul. Ez az összmennyiség magában foglalja a vizet, a kávét, a teát, a tejet és az ételben lévő vizet, nem csak a tiszta vizet. Többre van szükséged, amikor meleg van, amikor sokat izzadsz, vagy a nehezebb edzésnapokon.', sv: 'En enkel utgångspunkt är ungefär 30-35 ml vätska per kilo kroppsvikt per dag, vilket för många hamnar runt 2-2,5 liter. Den totalen innefattar vatten, kaffe, te, mjölk och vattnet i maten, inte bara rent vatten. Du behöver mer när det är varmt, när du svettas mycket, eller på tyngre träningsdagar.' },
			{ en: 'You do not need to count millilitres. The easiest check is your urine: clear to pale yellow means you are well hydrated, while dark yellow means drink more. Thirst is a fine guide for most people, so keep water within reach and sip through the day rather than gulping a lot at once.', fi: 'Sinun ei tarvitse laskea millilitroja. Helpoin tarkistus on virtsa: kirkas tai vaaleankeltainen tarkoittaa että olet hyvin nesteytetty, kun taas tummankeltainen tarkoittaa että juo lisää. Jano on useimmille hyvä opas, joten pidä vettä käden ulottuvilla ja juo pitkin päivää isojen kerta-annosten sijaan.', hu: 'Nem kell milliliterre számolnod. A legegyszerűbb ellenőrzés a vizeleted: a tiszta vagy halványsárga jó hidratáltságot jelez, míg a sötétsárga azt, hogy igyál többet. A szomjúság a legtöbb embernek jó iránytű, ezért tartsd a vizet kéznél, és kortyolgasd a nap során, ne pedig egyszerre dönts le sokat.', sv: 'Du behöver inte räkna milliliter. Den enklaste kontrollen är urinen: klar till ljusgul betyder att du är väl vätskebalanserad, medan mörkgul betyder drick mer. Törst är en bra vägledning för de flesta, så håll vatten inom räckhåll och drick smått genom dagen istället för att klunka mycket på en gång.' }
		]
	},
	{
		id: 'fibre',
		title: {
			en: 'Fibre',
			fi: 'Kuitu',
			hu: 'Rost',
			sv: 'Fiber'
		},
		summary: {
			en: 'Build toward about 14 g per 1000 kcal from vegetables, fruit, whole grains and legumes - and add it gradually.',
			fi: 'Rakenna kohti noin 14 g jokaista 1000 kcal:a kohti kasviksista, hedelmistä, täysjyvästä ja palkokasveista - ja lisää vähitellen.',
			hu: 'Építs kb. 14 g-ot 1000 kcal-onként zöldségből, gyümölcsből, teljes gabonából és hüvelyesekből - fokozatosan.',
			sv: 'Bygg mot cirka 14 g per 1000 kcal från grönsaker, frukt, fullkorn och baljväxter - och öka gradvis.'
		},
		body: [
			{ en: 'Fibre is the part of plant foods your body does not fully digest. It slows digestion, helps you feel full on fewer calories, and supports a healthy gut and regular bowels. A handy target is about 14 g of fibre for every 1000 kcal you eat, which for most people is roughly 25-35 g a day.', fi: 'Kuitu on kasviruokien osa, jota keho ei sulata täysin. Se hidastaa ruoansulatusta, auttaa tuntemaan kylläisyyttä pienemmällä kalorimäärällä ja tukee tervettä suolistoa ja säännöllistä vatsaa. Kätevä tavoite on noin 14 g kuitua jokaista syötyä 1000 kcal:a kohti, mikä on useimmille noin 25-35 g päivässä.', hu: 'A rost a növényi élelmiszerek azon része, amelyet a szervezeted nem emészt meg teljesen. Lassítja az emésztést, segít kevesebb kalóriából jóllakni, és támogatja az egészséges bélrendszert és a rendszeres emésztést. Praktikus célérték nagyjából 14 g rost minden elfogyasztott 1000 kcal-ra, ami a legtöbb embernél körülbelül napi 25-35 g.', sv: 'Fiber är den del av växtbaserad mat som kroppen inte smälter helt. Den bromsar matsmältningen, hjälper dig att känna dig mätt på färre kalorier och stödjer en frisk tarm och regelbunden mage. Ett behändigt mål är ungefär 14 g fiber för varje 1000 kcal du äter, vilket för de flesta är grovt 25-35 g om dagen.' },
			{ en: 'You reach it with everyday foods: vegetables and fruit, whole-grain bread and oats, brown rice, and especially legumes such as beans, lentils and chickpeas. Leaving the skins on potatoes and choosing whole-grain over white versions adds fibre with no effort.', fi: 'Saavutat sen arkiruoilla: kasviksilla ja hedelmillä, täysjyväleivällä ja kauralla, täysjyväriisillä ja erityisesti palkokasveilla kuten pavuilla, linsseillä ja kikherneillä. Perunan kuorten jättäminen ja täysjyvän valitseminen vaalean sijaan lisäävät kuitua vaivatta.', hu: 'Mindennapi ételekkel eléred: zöldséggel és gyümölccsel, teljes kiőrlésű kenyérrel és zabbal, barna rizzsel, és különösen hüvelyesekkel, mint a bab, a lencse és a csicseriborsó. Ha a burgonyán rajta hagyod a héját, és a fehér helyett a teljes kiőrlésű változatot választod, az erőfeszítés nélkül ad hozzá rostot.', sv: 'Du når det med vardagsmat: grönsaker och frukt, fullkornsbröd och havre, fullkornsris och särskilt baljväxter som bönor, linser och kikärtor. Att låta skalet sitta kvar på potatisen och välja fullkorn framför de ljusa varianterna lägger till fiber utan ansträngning.' },
			{ en: 'Increase fibre gradually over a week or two and drink enough water alongside it. Jumping from very little to a lot overnight often causes bloating and discomfort, while a slow build-up lets your gut adjust comfortably.', fi: 'Lisää kuitua vähitellen viikon tai kahden aikana ja juo riittävästi vettä sen rinnalla. Hyppy hyvin vähästä suureen kerralla aiheuttaa usein turvotusta ja epämukavuutta, kun taas hidas lisäys antaa suoliston sopeutua mukavasti.', hu: 'A rostot fokozatosan növeld egy-két hét alatt, és igyál mellé elég vizet. Ha nagyon kevésről egyik napról a másikra sokra ugrasz, az gyakran puffadást és kellemetlenséget okoz, míg a lassú felépítés kényelmesen engedi a bélrendszert alkalmazkodni.', sv: 'Öka fibern gradvis under en vecka eller två och drick tillräckligt med vatten vid sidan av. Att hoppa från mycket lite till mycket över en natt orsakar ofta uppblåsthet och obehag, medan en långsam upptrappning låter tarmen anpassa sig bekvämt.' }
		]
	},
	{
		id: 'fat-loss-tactics',
		title: {
			en: 'Losing fat',
			fi: 'Rasvanpudotus',
			hu: 'Fogyás',
			sv: 'Tappa fett'
		},
		summary: {
			en: 'A moderate deficit (about 0.5-1 percent of body weight a week), high protein, filling foods and daily steps.',
			fi: 'Maltillinen vaje (noin 0,5-1 prosenttia painosta viikossa), runsas proteiini, täyttävät ruoat ja päivittäiset askeleet.',
			hu: 'Mérsékelt deficit (kb. a testsúly 0,5-1 százaléka hetente), magas fehérje, laktató ételek és napi lépések.',
			sv: 'Måttligt underskott (cirka 0,5-1 procent av kroppsvikten per vecka), högt protein, mättande mat och dagliga steg.'
		},
		body: [
			{ en: 'Fat loss comes from a sustained calorie deficit, but moderate beats extreme. A sensible rate is about 0.5-1 percent of your body weight per week. Faster than that tends to cost muscle and energy and is hard to keep up. The slower end is often the smarter choice because it is easier to live with and protects your training.', fi: 'Rasvanpudotus tulee pitkäkestoisesta kalorivajeesta, mutta maltillinen voittaa äärimmäisen. Järkevä tahti on noin 0,5-1 prosenttia painosta viikossa. Sitä nopeampi vie yleensä lihasta ja energiaa ja on vaikea pitää yllä. Hitaampi pää on usein viisaampi valinta, koska sen kanssa on helpompi elää ja se suojaa harjoittelua.', hu: 'A zsírvesztés a tartós kalóriadeficitből ered, de a mérsékelt legyőzi a szélsőségest. Értelmes tempó a testsúly nagyjából 0,5-1 százaléka hetente. Az ennél gyorsabb általában izomba és energiába kerül, és nehéz fenntartani. A lassabb vég gyakran a bölcsebb választás, mert könnyebb vele együtt élni, és védi az edzésed.', sv: 'Fettförbränning kommer från ett ihållande kaloriunderskott, men måttligt slår extremt. En vettig takt är ungefär 0,5-1 procent av din kroppsvikt per vecka. Snabbare än så tenderar att kosta muskler och energi och är svår att hålla i. Den långsammare delen är ofta det smartare valet eftersom den är lättare att leva med och skyddar din träning.' },
			{ en: 'Make the deficit easy to tolerate. Keep protein high so you hold onto muscle and stay full, and lean on high-volume, low-calorie foods such as vegetables, salads, broth-based soups, berries and air-popped popcorn that fill the plate for few calories. These two habits do most of the work of managing hunger.', fi: 'Tee vajeesta helposti siedettävä. Pidä proteiini korkealla, jotta säilytät lihasta ja pysyt kylläisenä, ja nojaa runsasvolyymisiin, vähäkalorisiin ruokiin kuten kasviksiin, salaatteihin, liemikeittoihin, marjoihin ja ilmapaahdettuun popcorniin, jotka täyttävät lautasen pienellä kalorimäärällä. Nämä kaksi tapaa hoitavat suurimman osan nälän hallinnasta.', hu: 'Tedd könnyen elviselhetővé a deficitet. Tartsd magasan a fehérjét, hogy megtartsd az izmot és jóllakott maradj, és támaszkodj a nagy térfogatú, alacsony kalóriás ételekre, mint a zöldség, a saláta, a lében főtt leves, a bogyós gyümölcs és a légpattogatott popcorn, amelyek kevés kalóriával töltik meg a tányért. Ez a két szokás végzi el az éhségkezelés nagy részét.', sv: 'Gör underskottet lätt att tolerera. Håll proteinet högt så att du behåller muskler och håller dig mätt, och luta dig mot volymrik, kalorisnål mat som grönsaker, sallader, buljongbaserade soppor, bär och luftpoppat popcorn som fyller tallriken på få kalorier. De här två vanorna gör det mesta av jobbet med att hantera hungern.' },
			{ en: 'Daily movement helps more than extra cardio sessions. A step target you can hit most days keeps your energy output steady without leaving you ravenous the way long, hard cardio sometimes does. Resistance training stays the priority because it signals your body to keep the muscle you have.', fi: 'Päivittäinen liikkuminen auttaa enemmän kuin ylimääräiset kardioharjoitukset. Askeltavoite, jonka saavutat useimpina päivinä, pitää kulutuksen tasaisena ilman että jäät nälkäiseksi kuten pitkä, kova kardio joskus jättää. Voimaharjoittelu pysyy etusijalla, koska se viestii keholle säilyttää olemassa oleva lihas.', hu: 'A napi mozgás többet segít, mint az extra kardió alkalmak. Egy lépéscél, amelyet a legtöbb napon teljesítesz, egyenletesen tartja az energialeadásod anélkül, hogy farkaséhessé tenne, ahogy a hosszú, kemény kardió néha. Az erőedzés marad az elsődleges, mert azt jelzi a testednek, hogy tartsa meg a meglévő izmot.', sv: 'Daglig rörelse hjälper mer än extra konditionspass. Ett stegmål som du kan nå de flesta dagar håller din energiförbrukning stadig utan att lämna dig utsvulten som lång, tuff kondition ibland gör. Styrketräning förblir prioriteten eftersom den signalerar till kroppen att behålla de muskler du har.' },
			{ en: 'A useful self-check is the feeler week. Once in a while, eat at your estimated maintenance for a week and watch your weekly average. If it holds steady, you have found your true maintenance and can set the deficit from there with confidence. It also gives your appetite and mind a planned break from dieting.', fi: 'Hyödyllinen itsetarkistus on tunnusteluviikko. Aika ajoin syö arvioidulla ylläpidolla viikon ajan ja seuraa viikkokeskiarvoa. Jos se pysyy vakaana, olet löytänyt todellisen ylläpitosi ja voit asettaa vajeen siitä luottavaisin mielin. Se antaa myös ruokahalulle ja mielelle suunnitellun tauon dieetistä.', hu: 'Hasznos önellenőrzés a tapogatózó hét. Időnként egy héten át edd a becsült fenntartó kalóriádat, és figyeld a heti átlagot. Ha stabil marad, megtaláltad a valódi fenntartó szintedet, és onnantól magabiztosan állíthatod be a deficitet. Egyúttal tervezett szünetet ad az étvágyadnak és a fejednek a diétától.', sv: 'En användbar självkontroll är kännveckan. Ät med jämna mellanrum på ditt uppskattade underhåll under en vecka och följ ditt veckosnitt. Om det håller sig stadigt har du hittat ditt sanna underhåll och kan sätta underskottet därifrån med självförtroende. Det ger också din aptit och ditt sinne en planerad paus från bantningen.' }
		]
	},
	{
		id: 'muscle-gain-tactics',
		title: {
			en: 'Gaining muscle',
			fi: 'Lihaksen kasvatus',
			hu: 'Izomépítés',
			sv: 'Bygga muskler'
		},
		summary: {
			en: 'A small surplus (around 10 percent), protein first, and progressive training as the real driver.',
			fi: 'Pieni ylijäämä (noin 10 prosenttia), proteiini ensin, ja nouseva harjoittelu varsinaisena moottorina.',
			hu: 'Kis többlet (kb. 10 százalék), fehérje elöl, és a fokozatos edzés a valódi motor.',
			sv: 'Litet överskott (kring 10 procent), protein först, och progressiv träning som den verkliga drivkraften.'
		},
		body: [
			{ en: 'Muscle grows when training gives the body a reason to build it and food supplies the materials. The food part is a small calorie surplus, roughly 10 percent above maintenance. That is enough to support growth while keeping fat gain low. A huge surplus does not build muscle faster; it mostly adds fat you later have to lose.', fi: 'Lihas kasvaa, kun harjoittelu antaa keholle syyn rakentaa sitä ja ruoka tuo materiaalit. Ruokaosuus on pieni kaloriylijäämä, noin 10 prosenttia yli ylläpidon. Se riittää tukemaan kasvua pitäen samalla rasvan nousun pienenä. Valtava ylijäämä ei rakenna lihasta nopeammin; se lähinnä lisää rasvaa, joka pitää myöhemmin pudottaa.', hu: 'Az izom akkor nő, ha az edzés okot ad a testnek a felépítésére, és az étel biztosítja az anyagokat. Az étrendi rész egy kis kalóriatöbblet, nagyjából 10 százalékkal a fenntartó szint fölött. Ennyi elég a növekedés támogatásához, miközben alacsonyan tartja a zsírgyarapodást. A hatalmas többlet nem épít gyorsabban izmot; főleg zsírt rak fel, amelyet később le kell adnod.', sv: 'Muskler växer när träningen ger kroppen en anledning att bygga dem och maten levererar materialet. Matdelen är ett litet kaloriöverskott, grovt 10 procent över underhåll. Det räcker för att stödja tillväxt samtidigt som fettökningen hålls låg. Ett enormt överskott bygger inte muskler snabbare; det lägger mest till fett som du senare måste tappa.' },
			{ en: 'The real driver is the training, not the eating. Progressive overload, meaning you gradually add reps, sets or load over weeks, is what tells your body to adapt and grow. Eating in a surplus without that progression just makes you heavier. Keep protein at the priority level, about 1.6-2.0 g per kilogram, so the building blocks are always there.', fi: 'Varsinainen moottori on harjoittelu, ei syöminen. Nouseva kuormitus, eli lisäät vähitellen toistoja, sarjoja tai kuormaa viikkojen aikana, on se mikä kertoo keholle sopeutua ja kasvaa. Syöminen ylijäämässä ilman tätä etenemistä tekee sinusta vain painavamman. Pidä proteiini etusijatasolla, noin 1,6-2,0 g painokiloa kohti, jotta rakennusaineita on aina saatavilla.', hu: 'A valódi mozgatórugó az edzés, nem az étkezés. A fokozatos túlterhelés, vagyis hogy a hetek során lassan adsz hozzá ismétléseket, sorozatokat vagy súlyt, ez mondja a testednek, hogy alkalmazkodjon és nőjön. Ha többletben eszel e fejlődés nélkül, attól csak nehezebb leszel. Tartsd a fehérjét elsődleges szinten, nagyjából 1,6-2,0 g testsúlykilogrammonként, hogy az építőanyagok mindig rendelkezésre álljanak.', sv: 'Den verkliga drivkraften är träningen, inte ätandet. Progressiv överbelastning, alltså att du gradvis lägger till repetitioner, set eller belastning över veckor, är det som talar om för kroppen att anpassa sig och växa. Att äta i överskott utan den progressionen gör dig bara tyngre. Håll proteinet på prioritetsnivå, ungefär 1,6-2,0 g per kilo, så att byggstenarna alltid finns där.' },
			{ en: 'Expect a slow, honest pace. For most people a gain of roughly 0.25-0.5 kg per month of mostly lean weight is realistic, faster early on and slower with experience. Track your weekly average and your lifts; if both are creeping up over a month, the surplus is about right.', fi: 'Odota hidasta, rehellistä tahtia. Useimmille noin 0,25-0,5 kg kuukaudessa pääosin vähärasvaista painoa on realistista, nopeampaa alussa ja hitaampaa kokemuksen myötä. Seuraa viikkokeskiarvoa ja nostoja; jos molemmat hivuttautuvat ylös kuukauden aikana, ylijäämä on suunnilleen oikea.', hu: 'Számíts lassú, becsületes tempóra. A legtöbb embernél nagyjából havi 0,25-0,5 kg többnyire sovány tömeg gyarapodása reális, elején gyorsabban, a tapasztalattal lassabban. Kövesd a heti átlagod és az emeléseid; ha egy hónap alatt mindkettő felfelé kúszik, a többlet nagyjából megfelelő.', sv: 'Vänta dig en långsam, ärlig takt. För de flesta är en ökning på grovt 0,25-0,5 kg per månad av mestadels mager vikt realistiskt, snabbare i början och långsammare med erfarenhet. Följ ditt veckosnitt och dina lyft; om båda kryper uppåt över en månad är överskottet ungefär rätt.' }
		]
	},
	{
		id: 'tracking-and-adjusting',
		title: {
			en: 'Tracking and adjusting',
			fi: 'Seuranta ja säätäminen',
			hu: 'Követés és kiigazítás',
			sv: 'Mätning och justering'
		},
		summary: {
			en: 'Read the weekly average, not the daily number, and only change calories after two to three flat weeks.',
			fi: 'Lue viikkokeskiarvoa, älä päivittäistä lukua, ja muuta kaloreita vasta kahden tai kolmen tasaisen viikon jälkeen.',
			hu: 'A heti átlagot nézd, ne a napi számot, és csak két-három lapos hét után változtass a kalórián.',
			sv: 'Läs veckosnittet, inte dagssiffran, och ändra kalorierna först efter två till tre platta veckor.'
		},
		body: [
			{ en: 'Daily weight jumps around for reasons that have nothing to do with fat: salt, water, carbs, sleep and the bathroom all move the number. So judge progress by the weekly average instead. Weigh yourself most mornings under the same conditions and look at how this weeks average compares to last weeks. That trend line is the signal; a single day is noise.', fi: 'Päivittäinen paino heittelee syistä, joilla ei ole mitään tekemistä rasvan kanssa: suola, vesi, hiilihydraatit, uni ja vessassa käynti liikuttavat lukua. Arvioi siis kehitystä viikkokeskiarvon perusteella. Punnitse useimpina aamuina samoissa olosuhteissa ja katso, miten tämän viikon keskiarvo suhtautuu viime viikkoon. Tuo trendiviiva on signaali; yksittäinen päivä on kohinaa.', hu: 'A napi testsúly olyan okokból ugrál, amelyeknek semmi köze a zsírhoz: a só, a víz, a szénhidrát, az alvás és a mosdóhasználat mind mozgatja a számot. Ezért inkább a heti átlag alapján ítéld meg a fejlődést. Mérd magad a legtöbb reggel ugyanolyan körülmények között, és nézd meg, hogyan viszonyul ennek a hétnek az átlaga a múlt hetihez. Ez a trendvonal a jelzés; egyetlen nap csak zaj.', sv: 'Den dagliga vikten hoppar omkring av skäl som inte har något med fett att göra: salt, vatten, kolhydrater, sömn och toabesök flyttar alla siffran. Bedöm alltså framsteg utifrån veckosnittet istället. Väg dig de flesta morgnar under samma förhållanden och titta på hur denna veckas snitt ställer sig mot förra veckans. Den trendlinjen är signalen; en enskild dag är brus.' },
			{ en: 'Give a plan time before changing it. Two to three weeks of a flat average when you wanted movement is the cue to adjust, not a single stalled day. When you do adjust, change food by a small step (about 150-250 kcal) rather than a big swing, then watch for another two to three weeks. Small, patient changes keep you in control.', fi: 'Anna suunnitelmalle aikaa ennen muutosta. Kaksi tai kolme viikkoa tasaista keskiarvoa silloin kun halusit liikettä on merkki säätää, ei yksittäinen pysähtynyt päivä. Kun säädät, muuta ruokaa pienellä askeleella (noin 150-250 kcal) suuren heilahduksen sijaan, ja seuraa sitten taas kaksi tai kolme viikkoa. Pienet, kärsivälliset muutokset pitävät sinut hallinnassa.', hu: 'Adj időt egy tervnek, mielőtt megváltoztatnád. Két-három hét sík átlag, amikor mozgást szerettél volna, az a jel a módosításra, nem egyetlen megrekedt nap. Amikor módosítasz, kis lépéssel (nagyjából 150-250 kcal) változtass az étkezésen, ne nagy kilengéssel, majd figyeld újabb két-három héten át. A kis, türelmes változtatások tartanak kézben.', sv: 'Ge en plan tid innan du ändrar den. Två till tre veckor med ett platt snitt när du ville ha rörelse är signalen att justera, inte en enda dag som stannat av. När du justerar, ändra maten med ett litet steg (ungefär 150-250 kcal) snarare än en stor sväng, och följ sedan upp i ytterligare två till tre veckor. Små, tålmodiga ändringar håller dig i kontroll.' },
			{ en: 'You do not have to weigh every gram of food forever. Many people track closely for a few weeks to learn what their portions look like, then loosen to spot-checks. The plate method, a consistent routine and the weekly weigh-in trend are enough to keep most people on course.', fi: 'Sinun ei tarvitse punnita jokaista ruokagrammaa ikuisesti. Moni seuraa tarkasti muutaman viikon oppiakseen miltä omat annokset näyttävät, ja löysää sitten pistokokeisiin. Lautasmalli, johdonmukainen rutiini ja viikoittainen punnitustrendi riittävät pitämään useimmat kurssilla.', hu: 'Nem kell örökké minden grammot lemérned. Sokan néhány hétig szorosan követik, hogy megtanulják, hogyan néznek ki az adagjaik, majd lazítanak a szúrópróbaszerű ellenőrzésre. A tányérmódszer, egy következetes rutin és a heti mérési trend a legtöbb embert pályán tartja.', sv: 'Du behöver inte väga varje gram mat för alltid. Många följer noga i några veckor för att lära sig hur portionerna ser ut, och löser sedan upp till stickprov. Tallriksmodellen, en beständig rutin och den veckovisa vägningstrenden räcker för att hålla de flesta på rätt kurs.' }
		]
	},
	{
		id: 'what-to-learn-next',
		title: {
			en: 'Worth understanding next',
			fi: 'Seuraavaksi ymmärrettävää',
			hu: 'Amit érdemes megérteni',
			sv: 'Värt att förstå härnäst'
		},
		summary: {
			en: 'A few neutral topics worth reading credibly about as you go deeper - no rules, just understanding.',
			fi: 'Muutama neutraali aihe, joista kannattaa lukea luotettavasti kun syvennyt - ei sääntöjä, vain ymmärrystä.',
			hu: 'Néhány semleges téma, amiröl érdemes hiteles forrásból olvasni - nincs szabály, csak megértés.',
			sv: 'Några neutrala ämnen värda att läsa trovärdigt om när du fördjupar dig - inga regler, bara förståelse.'
		},
		body: [
			{ en: 'Once the basics above feel familiar, a little deeper reading helps the pieces click together. Two ideas are worth understanding well because everything else sits on top of them: energy balance over time, and protein distribution across the day. When those two make intuitive sense, most nutrition advice becomes easy to judge.', fi: 'Kun yllä olevat perusasiat tuntuvat tutuilta, hieman syvempi lukeminen auttaa palasia loksahtamaan yhteen. Kaksi ajatusta kannattaa ymmärtää hyvin, koska kaikki muu lepää niiden päällä: energiatasapaino ajan yli ja proteiinin jakautuminen päivälle. Kun nämä kaksi tuntuvat intuitiivisilta, useimmat ravitsemusneuvot on helppo arvioida.', hu: 'Ha a fenti alapok ismerősnek érződnek, egy kis mélyebb olvasás segít, hogy a darabok összeálljanak. Két gondolatot érdemes jól megérteni, mert minden más ezeken nyugszik: az energiaegyensúly időben, és a fehérje napon belüli eloszlása. Amikor ez a kettő intuitívan érthetővé válik, a legtöbb táplálkozási tanácsot könnyű megítélni.', sv: 'När grunderna ovan känns bekanta hjälper lite djupare läsning bitarna att falla på plats. Två idéer är värda att förstå väl eftersom allt annat vilar på dem: energibalans över tid och proteinfördelning över dagen. När de två känns intuitiva blir de flesta näringsråd lätta att bedöma.' },
			{ en: 'Sleep and recovery are also worth a read. Short or poor sleep tends to raise appetite and make training feel harder, so they quietly affect both fat loss and muscle gain. Understanding why recovery matters often does more for results than any new food rule.', fi: 'Uni ja palautuminen ovat myös lukemisen arvoisia. Lyhyt tai huono uni nostaa yleensä ruokahalua ja tekee harjoittelusta raskaamman tuntuista, joten ne vaikuttavat hiljaa sekä rasvanpudotukseen että lihaksen kasvuun. Sen ymmärtäminen miksi palautuminen on tärkeää tekee tuloksille usein enemmän kuin mikään uusi ruokasääntö.', hu: 'Az alvás és a regeneráció is olvasásra érdemes. A rövid vagy rossz alvás általában növeli az étvágyat és nehezebbé teszi az edzést, így csendben hat mind a zsírvesztésre, mind az izomépítésre. Annak megértése, miért fontos a regeneráció, gyakran többet tesz az eredményekért, mint bármilyen új étkezési szabály.', sv: 'Sömn och återhämtning är också värda en läsning. Kort eller dålig sömn tenderar att höja aptiten och göra träningen tyngre, så de påverkar i tysthet både fettförbränning och muskeltillväxt. Att förstå varför återhämtning är viktig gör ofta mer för resultaten än någon ny matregel.' },
			{ en: 'Most useful of all is learning to tell evidence from marketing. Be a little skeptical of products that promise fast results, secret tricks, or anything that sounds too good to be true. Look for guidance from public health authorities, registered dietitians and researchers rather than supplement sellers. Knowing how to read a claim is the skill that protects you for life.', fi: 'Hyödyllisintä kaikista on oppia erottamaan näyttö markkinoinnista. Suhtaudu hieman epäillen tuotteisiin, jotka lupaavat nopeita tuloksia, salaisia temppuja tai mitä tahansa mikä kuulostaa liian hyvältä ollakseen totta. Etsi ohjeita kansanterveysviranomaisilta, laillistetuilta ravitsemusterapeuteilta ja tutkijoilta lisäravinteiden myyjien sijaan. Taito lukea väitettä on se, joka suojaa sinua koko elämän.', hu: 'A leghasznosabb mindenek közül megtanulni megkülönböztetni a bizonyítékot a marketingtől. Légy egy kicsit szkeptikus a gyors eredményt, titkos trükköket ígérő termékekkel, vagy bármivel, ami túl szépnek hangzik ahhoz, hogy igaz legyen. Inkább közegészségügyi hatóságoktól, dietetikusoktól és kutatóktól keress útmutatást, mint étrend-kiegészítőket árusítóktól. Az a képesség, hogy el tudsz olvasni egy állítást, az a készség, ami egész életedben megvéd.', sv: 'Mest användbart av allt är att lära sig skilja belägg från marknadsföring. Var lite skeptisk mot produkter som lovar snabba resultat, hemliga knep eller något som låter för bra för att vara sant. Sök vägledning från folkhälsomyndigheter, legitimerade dietister och forskare snarare än kosttillskottssäljare. Att veta hur man läser ett påstående är den färdighet som skyddar dig livet ut.' },
			{ en: 'A closing note: this page is general education, not medical or personalized dietary advice. If you have a health condition, are pregnant, are under 18, or have a history of disordered eating, talk to a doctor or a registered dietitian before making big changes.', fi: 'Lopuksi: tämä sivu on yleistä tietoa, ei lääketieteellistä tai henkilökohtaista ravitsemusneuvontaa. Jos sinulla on terveysongelma, olet raskaana, alle 18-vuotias tai sinulla on taustaa häiriintyneestä syömisestä, keskustele lääkärin tai laillistetun ravitsemusterapeutin kanssa ennen suuria muutoksia.', hu: 'Zárógondolat: ez az oldal általános ismeretterjesztés, nem orvosi vagy személyre szabott étrendi tanács. Ha egészségügyi problémád van, terhes vagy, 18 év alatti, vagy van előzményed evészavarral, beszélj orvossal vagy dietetikussal, mielőtt nagy változtatásokba kezdesz.', sv: 'En avslutande notis: den här sidan är allmän utbildning, inte medicinska eller personliga kostråd. Om du har en sjukdom, är gravid, är under 18 eller har en historia av störda ätbeteenden, prata med en läkare eller en legitimerad dietist innan du gör stora förändringar.' }
		]
	}
];
